### ISSUE TITLE
No support for datetime.date objects. 

### ISSUE THREAD

**Issue by esagara** [cirlabs/miditime#2]
Requires date objects to be datetime objects.

**Comment by mikejcorey** [comment]
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/esagara/.envs/water/local/lib/python2.7/site-packages/django/core/management/**init**.py", line 338, in execute_from_command_line
    utility.execute()
  File "/home/esagara/.envs/water/local/lib/python2.7/site-packages/django/core/management/**init**.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/esagara/.envs/water/local/lib/python2.7/site-packages/django/core/management/base.py", line 390, in run_from_argv
    self.execute(_args, *_cmd_options)
  File "/home/esagara/.envs/water/local/lib/python2.7/site-packages/django/core/management/base.py", line 441, in execute
    output = self.handle(_args, *_options)
  File "/home/esagara/Code/california_water/reservoirs/management/commands/play_a_reservoir.py", line 21, in handle
    data_epoched = [{d['days_since_epoch']: midi.days_since_epoch(d['date']), d['amount'] : d['percentage']} for d in data]
  File "/home/esagara/.envs/water/local/lib/python2.7/site-packages/miditime/MIDITime.py", line 55, in days_since_epoch
    return (input - normalized_epoch).total_seconds()/60/60/24  # How many days, with fractions
TypeError: unsupported operand type(s) for -: 'datetime.date' and 'datetime.datetime'
